### ISSUE TITLE
Add a Toggle Option in config to Disable Channels

### ISSUE THREAD

**Issue by MrRagtime** [JamieIsGeek/ProxyDiscordSRV#3]
#### For some reason, there is a **"playskywars"** channel even though I have no skywars server on my proxy config.
> ![image](https://github.com/JamieIsGeek/ProxyDiscordSRV/assets/134163817/f707be73-dc17-4c7e-8be9-97eabeb6baf6)
> **If you can add a "false" & "true" option for disabling all channels listed in the category. That would be very helpful!**

**Comment by JamieIsGeek** [comment]
Sorry for the delay, what exactly do you mean by "If you can add a "false" & "true" option for disabling all channels listed in the category."?

**Comment by MrRagtime** [comment]
The config uses a category ID, and makes channels that I have listed in my proxy config, but it made a "playskywars" channel which is not mentioned anywhere on the proxy. I was wondering if you can make it toggleable for each channel, or just use channel ID instead of category ID.

> Sorry for the delay, what exactly do you mean by "If you can add a "false" & "true" option for disabling all channels listed in the category."?

**Comment by JamieIsGeek** [comment]
Odd, it should only make channels for servers that are listed in your bungeecord config.yml.

I've never seen it do anything like that before in the multiple times I've done a fresh install of this plugin. Could you double check your config.yml for bungeecord?

**Comment by MrRagtime** [comment]
I double checked, and it still says my servers. **"playskywars"** is not listed there.
![image](https://github.com/JamieIsGeek/ProxyDiscordSRV/assets/134163817/025881c2-5c02-4f11-b795-3a56452b6841)

Here is the Discord channel
![image](https://github.com/JamieIsGeek/ProxyDiscordSRV/assets/134163817/4c5e319d-bc4f-4ad2-910c-17bab1b59fc8)

**Comment by JamieIsGeek** [comment]
It will look something like this, not under the priorities section
<img width="322" alt="Screenshot 2024-03-08 at 14 51 17" src="https://github.com/JamieIsGeek/ProxyDiscordSRV/assets/109307647/2a0da9ab-e5f2-443e-87e1-dc755ce3318b">

**Comment by MrRagtime** [comment]
Mb, here.
![image](https://github.com/JamieIsGeek/ProxyDiscordSRV/assets/134163817/30a28dce-ed82-4f44-8e78-19523ff17d30)

**Comment by JamieIsGeek** [comment]
What happens if you delete the playskywars channel and restart your proxy?

**Comment by MrRagtime** [comment]
I did that not too long ago, and it just recreated the skywars channel.

**Comment by JamieIsGeek** [comment]
Well I don't think its the plugin since all it does is grab all the servers attached to your proxy. You're 100% sure you have not got "playskywars" anywhere in any server management configs?

**Comment by MrRagtime** [comment]
I'm sure. Though could other plugins effect the config?

**Comment by JamieIsGeek** [comment]
You don't define what servers are created in the config for this plugin however if it detects other servers on your network it will create them. You don't use anything like ServerManager or anything like that?

**Comment by MrRagtime** [comment]
Isn't there just the bungee / waterfall "config.yml" for defining server(s), or is there another config somewhere else?

Edit: My bad, I read it wrong.
Do you mean my local network, or the server-pc it self?

**Comment by JamieIsGeek** [comment]
No on the server network you're using, so anything that is connected to your proxy server

**Comment by MrRagtime** [comment]
This sounde more like a issue on my side, and not the plugins code.

Thank you for all your help for 7 days though!
