### ISSUE TITLE
@everyone Issue

### ISSUE THREAD

**Issue by RyuguDev** [JamieIsGeek/ProxyDiscordSRV#4]
Your plugin is good in itself, actually perfect because in combination with a Viaproxy you can also bridge with Beta and Alpha servers via a bungee cord. The only HUGE problem I saw was: as a player you can roll in the Minecraft chat and ping @everyone, what could be abused to fuck people off. This is fixed in the normal DiscordSRV, I have no idea how they did it there, but my tip to you is to make the message and the prefix etc. everything exactly like in the real DiscordSRV, so that you can (fox example) use ``` to fix it

**Comment by JamieIsGeek** [comment]
I believe just removing the @everyone permission from your bot will also fix this issue. However I will still look into another way to fix that.

**Comment by JamieIsGeek** [comment]
Fixed in commit [dfdde29](https://github.com/JamieIsGeek/ProxyDiscordSRV/commit/dfdde290fceb2982592550e9d32e539a54bbd944)
